### ISSUE TITLE
Doesn't check to see if a blue bin need to be refilled

### ISSUE THREAD

**Issue by raidancampbell** [lucbettaieb/refill_checker#1]
expected behavior: checks to see if a blue bin need to be refilled

observed behavior: none

Possible remedy: check to see if a blue bin need to be refilled

**Comment by lucbettaieb** [comment]
oh..................

**Comment by lucbettaieb** [comment]
one sec

**Comment by lucbettaieb** [comment]
Addressed: https://github.com/lucbettaieb/refill_checker/commit/0a1b57d8d330075eb5a8cc0f4cb574ba7f2a8931

**Comment by raidancampbell** [comment]
thanks man, this code is exactly what I needed to continue businessing

**Comment by lucbettaieb** [comment]
:+1:
